// Criação de um usuário
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Erick",
    "username": "Erick8080"
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "João",
    "username": "Joaquim33"
}
